cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('<cupboard_id>/<code>',
         views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_item, name='remove_item'),
] 

cupboards/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_cupboards, name='cupboards'),
    path('<int:cupboard_id>', views.cupboard_details, name='cupboard_details'),
    path('<int:cupboard_id>/', views.calculated_cupboard,
         name='calculated_cupboard'),
    path('<int:cupboard_id>/<height>/<width>/<depth>/<shelves>/<price>/<postage>', views.cart_cupboard, name='cart_cupboard'),
    path('add_design/', views.add_design, name='add_design'),
    path('add_material/', views.add_material, name='add_material'),
    path('edit_design/<int:cupboard_id>', views.edit_design, name='edit_design'),
    path('edit_material/<int:material_id>', views.edit_material, name='edit_material'),
    path('materials/', views.list_materials, name='materials'),
    path('delete_material/<int:material_id>', views.delete_material, name='delete_material'),
    path('delete_design/<int:cupboard_id>', views.delete_design, name='delete_design'),
]

custom_cupboards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('cupboards/', include('cupboards.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cupboards/models.py
from django.db import models

# Create your models here.


class Material(models.Model):

    name = models.CharField(max_length=254)
    display_name = models.CharField(max_length=254, null=True, blank=True)
    price_per_m2 = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False)

    def __str__(self):
        return self.name

    def get_display_name(self):
        return self.display_name


class Type(models.Model):
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Cupboard(models.Model):

    design_id = models.CharField(max_length=6)
    type = models.ForeignKey('Type', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    material = models.ForeignKey('Material', null=True, blank=False,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    description = models.TextField()
    design_surcharge = models.DecimalField(max_digits=6, decimal_places=2)
    example_price = models.DecimalField(max_digits=6, decimal_places=2)
    main_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name 


class Image(models.Model):
    file_name = models.ImageField(null=True, blank=True)
    cupboard = models.ForeignKey(Cupboard, on_delete=models.CASCADE)
    main_image = models.BooleanField (null=False, blank=False, default=False)

    def __str__(self):
        return self.file_name.path

cupboards/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Cupboard, Type, Material, Image

# Add a cupboard design
class DesignForm(forms.ModelForm):

    class Meta:
        model = Cupboard
        fields = '__all__'

    main_image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        types = Type.objects.all()
        friendly_names = [(t.id, t.get_friendly_name()) for t in types]
        self.fields['type'].choices = friendly_names
        
        materials = Material.objects.all()
        display_names = [(m.id, m.get_display_name()) for m in materials]
        self.fields['material'].choices = display_names

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

    # Add a material
class MaterialForm(forms.ModelForm):

    class Meta:
        model = Material
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

cupboards/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required

from .models import Cupboard, Material, Type, Image
from .forms import DesignForm, MaterialForm

# Create your views here.


def all_cupboards(request):
    """ A view to show all cupboards, including sorting and search queries """

    cupboards = Cupboard.objects.all()
    query = None
    type = None
    all_types = Type.objects.all()
    types = all_types
    sort = None
    direction = None

    if request.GET:

        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                cupboards = cupboards.annotate(lower_name=Lower('name'))

            if sortkey == 'price':
                sortkey = 'example_price'

            if sortkey == 'material':
                sortkey = 'material__name'

            if sortkey == 'type':
                sortkey = 'type__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            cupboards = cupboards.order_by(sortkey)
            
        if 'type' in request.GET:
            types = request.GET['type'].split(',')
            cupboards = cupboards.filter(type__name__in=types)
            type = Type.objects.filter(name__in=types)[0]
            
        print(type)

        if 'q' in request.GET:
            query = request.GET['q']

            if not query:
                messages.error(request, "Please enter some search criteria.")
                return redirect(reverse('cupboards'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            cupboards = cupboards.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'cupboards': cupboards,
        'search_term': query,
        'all_types': all_types,
        'type': type,
        'types': types,
        'current_sorting': current_sorting,
    }

    return render(request, 'cupboards/cupboards.html', context) 


def cupboard_details(request, cupboard_id):
    """ A view to show detailed cupdoard information and the user to select 
    their specifications and receive a quote"""

    cupboard = get_object_or_404(Cupboard, pk=cupboard_id)

    max_height = 2400
    max_width = 2400
    max_depth = 600
    min_depth = 150

    if cupboard.type.name == "cupboard":
        min_height = 400
        min_width = 400
    else:
        min_height = 200
        min_width = 200

    context = {
        'cupboard': cupboard,
        'max_height': max_height,
        'max_width': max_width,
        'max_depth': max_depth,
        'min_height': min_height,
        'min_width': min_width,
        'min_depth': min_depth
    }

    return render(request, 'cupboards/cupboard_details.html', context) 


def calculated_cupboard(request, cupboard_id):
    """ A view to calculate the cost of a cupboard after the user has entered their required dimensions and number of shelves in the form on the product_details template, then return an updated template showing the cost for those dimensions (dimensions also rendered back to them)"""

    cupboard = get_object_or_404(Cupboard, pk=cupboard_id)

    type = get_object_or_404(Type, pk=cupboard.type.id)

    material = get_object_or_404(Material, pk=cupboard.material.id)

    if request.method == "POST":
        height = int(request.POST.get("height"))
        width = int(request.POST.get("width"))
        depth = int(request.POST.get("depth"))
        shelves = int(request.POST.get("shelves"))

    price_per_mm2 = float(material.price_per_m2)/1000000
       
    """ Calculation.  Shelves are multiplied by 10 as there
    is a £10 cutting fee per shelf"""

    if type.name == "cupboard":
        area = (height*depth*2) + (height*width*2) + (width*depth*(2+shelves))
           
# or if shelving has not front
    else:
        area = (height*depth*2) + (height*width) + (width*depth*(2+shelves))
            
    cost = (area * price_per_mm2) + float(cupboard.design_surcharge) +(shelves*10)

    if float(area/10000) <= 732:
        postage = 10.00
    if 733 <= float(area/10000) <= 1488:
        postage = 20.00
    if 1489 <= float(area/10000) <= 2164:
        postage = 30.00
    if 2165 <= float(area/10000) <= 2880:
        postage = 40.00

    print(postage)

    H = height
    D = depth
    W = width
    S = shelves
    cost = round(cost, 2)
    code = f"{H}#{W}#{D}#{S}#{cost}#{postage}"

    max_height = 2400
    max_width = 2400
    max_depth = 600
    min_depth = 150

    if type.name == "cupboard":
        min_height = 400
        min_width = 400
    else:
        min_height = 200
        min_width = 200

    context = {
        'H': H,
        'D': D,
        'W': W,
        'S': S,
        'cost': cost,
        'cupboard': cupboard,
        'type': type,
        'code': code,
        'max_height': max_height,
        'max_width': max_width,
        'max_depth': max_depth,
        'min_height': min_height,
        'min_width': min_width,
        'min_depth': min_depth,
        'postage': postage
    }

    return render(request, 'cupboards/calculated_cupboard.html', context)


def cart_cupboard(request, cupboard_id, height, width, depth, shelves, price, postage):

    cupboard = get_object_or_404(Cupboard, pk=cupboard_id)

    type = get_object_or_404(Type, pk=cupboard.type.id)

    material = get_object_or_404(Material, pk=cupboard.material.id)


    H=height
    W = width
    D = depth
    S = shelves 
    cost = price
    postage = postage
    code = f"{H}#{W}#{D}#{S}#{cost}#{postage}"

    max_height = 2400
    max_width = 2400
    max_depth = 600
    min_depth = 150

    if type.name == "cupboard":
        min_height = 400
        min_width = 400
    else:
        min_height = 200
        min_width = 200

    context = {
        'H': H,
        'D': D,
        'W': W,
        'S': S,
        'cost': cost,
        'cupboard': cupboard,
        'type': type,
        'code': code,
        'max_height': max_height,
        'max_width': max_width,
        'max_depth': max_depth,
        'min_height': min_height,
        'min_width': min_width,
        'min_depth': min_depth,
        'postage': postage
    }

    return render(request, 'cupboards/calculated_cupboard.html', context)


@login_required
def add_design(request):
    """ Add a new design to the database"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorised to do this.')
        return redirect(reverse('home'))
   
    if request.method == 'POST':
        form = DesignForm(request.POST, request.FILES)
        if form.is_valid():
            cupboard = form.save()
            messages.success(request, 'Design successfully added.')
            return redirect(reverse('cupboard_details', args=[cupboard.id]))
        else:
            messages.error(request, 'Failed to add design. Please ensure the form is valid.')
    else:
        form = DesignForm()

    template = 'cupboards/add_design.html'

    context = {
        "form": form,
    }
    return render(request, template, context)


@login_required
def add_material(request):
    """ Add a new material to the database"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorised to do this.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Material successfully added.')
            return redirect('materials')
        else:
            messages.error(request, 'Failed to add material. Please ensure the form is valid.')
    else:
        return redirect('materials')


def list_materials(request):
    """ A view to show more detailed information about te materials available and a link for admin to edit materials in the database"""

    materials = Material.objects.all()
    form = MaterialForm()

    context = {
        'materials': materials,
        'form': form
    }

    return render(request, 'cupboards/materials.html', context) 


@login_required
def edit_design(request, cupboard_id):
    """ Edit a cupboard or shelving unit design """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorised to do this.')
        return redirect(reverse('home'))

    cupboard = get_object_or_404(Cupboard, pk=cupboard_id)
    if request.method == 'POST':
        form = DesignForm(request.POST, request.FILES, instance=cupboard)
        if form.is_valid():
            form.save()
            messages.success(request, 'Design successfully updated.')
            return redirect(reverse('cupboard_details', args=[cupboard.id]))
        else:
            messages.error(request, 'Failed to update design. Please ensure the form is valid.')
    else:
        form = DesignForm(instance=cupboard)

    template = 'cupboards/edit_design.html'
    context = {
        'form': form,
        'cupboard': cupboard
    }
    return render(request, template, context)


@login_required
def edit_material(request, material_id):
    """ Edit a material """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorised to do this.')
        return redirect(reverse('home'))

    material = get_object_or_404(Material, pk=material_id)
    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES, instance=material)
        if form.is_valid():
            form.save()

cupboards/templates/cupboards/add_design.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="logo-font my-4 text-center">Add a Design</h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8 offset-md-2 offset-lg-3 col-lg-6">
                <form method="POST" action="{% url 'add_design' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'main_image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-center mt-1 mb-3">
                        <button class="btn red-theme-color rounded-0 font-weight-bold my-1" type="submit">Add Design</button>
                        <a class="btn light-theme-color rounded-0 font-weight-bold cancel-btn my-1" href="{%url 'cupboards'%}?type=cupboard,shelving">Cancel</a>
                    </div>
                </form>
            </div>            
        </div>       
    </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
    <script>
        $("#id_design_id").val("");
        $("#id_name").val("");
        $("#id_description").val("");
        $("#id_design_surcharge").val("");
        $("#id_example_price").val("");
        $("#id_material").val("");
        $("#id_type").val("");
    </script>

{% endblock %}

cupboards/templates/cupboards/add_design_material.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="logo-font my-4 text-center">Product Management</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <h5 class="text-center">Add a Design</h5>
                <form method="POST" action="{% url 'add_design' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form1 %}
                        {% if field.name != 'main_image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-center mt-1 mb-4">
                        <button class="btn red-theme-color rounded-0 font-weight-bold" type="submit">Add Design</button>
                        <a class="btn light-theme-color rounded-0 font-weight-bold cancel-btn" href="{%url 'cupboards'%}?type=cupboard,shelving">Cancel</a>
                    </div>
                </form>
            </div>            

        <div class="col-12 col-md-6">
            <h5 class="text-center">Add a Material</h5>
            <form method="POST" action="{% url 'add_material' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form2 | crispy }}
                <div class="text-center my-4">
                    <button class="btn red-theme-color rounded-0 font-weight-bold" type="submit">Add Material</button>
                    <a class="btn light-theme-color cancel-btn rounded-0 font-weight-bold" href="{%url 'cupboards'%}?type=cupboard,shelving">Cancel</a>
                </div>
            </form>
         
        </div>  
        </div>       
    </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

cupboards/templates/cupboards/calculated_cupboard.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 text-center text-md-left">
            <div class="image-wrapper col-12 col-sm-10 offset-sm-1 col-md-12 offset-md-0 mt-3 mt-md-5">
                {% if cupboard.main_image %}
                <img class="card-img-top img-fluid mx-auto" src="{{ cupboard.main_image.url }}"
                    alt="{{ cupboard.name }}">
                {% else %}
                <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ cupboard.name }}">
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 p-0 px-md-2 text-center text-md-left">
            <div class="card border-0 m-3 mt-md-5 p-md-3 pb-3 light-theme-color ml-md-0 mr-md-4">
                <h3 class="card-header border-0 light-theme-color mt-3 mt-md-0 mt-lg-1">{{cupboard.name}}</h3>
                <p class="pl-md-3 mb-2 ml-4 mr-4 m-md-0">{{cupboard.description}}</p>
                <h6 class="pl-md-3 mb-1">Example price: £{{cupboard.example_price}} <small
                        class="d-none d-lg-block small">(for cupboard of dimensions: H: 1500mm / W: 1000mm / D:
                        500mm with 3 shelves.)</small></h6>
                <p class="pl-md-3 mb-1 example small d-lg-none">(for cupboard of dimensions:</p>
                <p class="pl-md-3 mb-1 small d-lg-none">H: 1500mm / W: 1000mm / D: 500mm with 3 shelves.)</p>
            </div>
            <div class="card border-0 m-3 mr-4 mt-4 p-md-3 pb-3 ml-md-0 pl-lg-0 pr-lg-0 red-theme-color">
                <form class="" action="{% url 'calculated_cupboard' cupboard.id %}" method="POST">
                    {% csrf_token %}
                    <div class="container-fluid">
                        <div class="row pr-lg-0 pt-1">
                            <div class="col-12 text-center text-lg-center col-lg-8 text-lg-left">
                                <h5 class="card-header border-0 red-theme-color mt-1 pl-lg-1 pt-0 pt-2 pb-1">Update Your
                                    Dimensions:</h5>
                                <h6 class="mb-0"><small><strong>Max: </strong>H: {{max_height}}mm / W: {{max_width}}mm /
                                        D: {{max_depth}}mm</small></h6>
                                <h6><small><strong>Min: </strong>H: {{min_height}}mm / W: {{min_width}}mm / D:
                                        {{min_depth}}mm</small></h6>
                                <div class="row pr-5 pt-2">
                                    <div class="col-6 pl-0 pr-3 text-right">
                                        <label for="height" class="">Height:</label>
                                    </div>
                                    <div class="col-6 text-left pl-0">
                                        <input id="height" class="dim-input validate mb-1" type="number" name="height"
                                            placeholder="{{H}}" minlength="1" maxlength="" max="{{max_height}}"
                                            min="{{min_height}}" value="{{H}}" required> mm
                                    </div>
                                </div>
                                <div class="row pr-5">
                                    <div class="col-6 pl-0 pr-3 text-right">
                                        <label for="width" class="">Width:</label>
                                    </div>
                                    <div class="col-6 text-left pl-0">
                                        <input id="width" class="dim-input validate my-1" type="number" name="width"
                                            placeholder="{{W}}" minlength="1" maxlength="4" max="{{max_width}}"
                                            min="{{min_width}}" value="{{W}}" required> mm</div>
                                </div>
                                <div class="row pb-1 pr-5">
                                    <div class="col-6 pl-0 pr-3 text-right">
                                        <label for="depth" class="">Depth:</label>
                                    </div>
                                    <div class="col-6 text-left pl-0">
                                        <input id="depth" class="dim-input validate mt-1" type="number" name="depth"
                                            placeholder="{{D}}" minlength="1" maxlength="4" max="{{max_depth}}"
                                            min="{{min_depth}}" value="{{D}}" required> mm
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 text-center col-lg-4 pl-lg-0 pr-lg-4">
                                <h5 class="card-header border-0 red-theme-color mt-1 pt-0 pl-lg-0 pt-lg-2">Select number
                                    of shelves:</h5>
                                <div class="select-wrapper">
                                    <select name="shelves" id="shelves" class="text-center">
                                        <option value="{{S}}">{{S}}</option>
                                        <option value="0">0</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="5">6</option>
                                        <option value="5">7</option>
                                        <option value="5">8</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-center pt-3">
                                <button type="submit" class="btn btn-lg light-theme-color">Recalculate</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12  p-0  text-center text-md-left">
            <div class="card border-2 border-black
                m-3 mt-lg-5 pb-3 mx-lg-5 white" id="calculation">
                <strong>
                    <h5 class="ml-md-5 mb-0 pt-2">Cost for {{type.friendly_name | lower}} of <br class=" d-md-none">
                        H: {{H}} mm / W: {{W}} mm / D: {{D}} mm<br class="d-md-none">
                        with {{S}} shelves: </h5>
                </strong>

                <div class="row text-center ">
                    <div class="col-12 pt-3">
                        <h3 class="text-center">£ {{cost}}</h3>
                        <h6 class="text-center">Delivery: £{{postage}}</h6>
                    </div>
                </div>
                <form class="form text-center" action="{% url 'add_to_cart' cupboard.id code %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 text-center pt-2">
                            <div class="form-group mr-5 pr-3">
                                <label for="quantity" class="">Quantity:</label>
                                <button
                                    class="decrement-qty btn plus-minus btn-sm light-theme-color rounded-0 decrement-qty_{{ item.item_id }} align-middle"
                                    data-item_id="{{ item.item_id }}">
                                    <span>
                                        <i class="fas fa-minus fa-sm"></i>
                                    </span>
                                </button>
                                <input id="quantity"
                                    class="number-input id_qty_{{ item.item_id }} qty_input align-middle text-center"
                                    type="number" name="quantity" value="1" minlength="1" maxlength="5">
                                <button
                                    class="increment-qty increment-qty_{{ item.item_id }} btn plus-minus btn-sm light-theme-color rounded-0 align-middle"
                                    data-item_id="{{ item.item_id }}">
                                    <span>
                                        <i class="fas fa-plus fa-sm"></i>
                                    </span>
                                </button>
                            </div>
                        </div>
                        <div class="col-12 text-center pt-2">
                            <button type="submit" class="btn btn-lg red-theme-color">Add to Cart</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-12 pt-1 pt-md-3 pb-4 text-center">
            <h5>
                <a href="{% url 'view_cart' %}" class="text-black">View Cart </a> | 
                <a href="{%url 'cupboards'%}" class="text-black"> Back to designs</a></h5>

        </div>

    </div>
</div>
{% endblock%}

{% block postloadjs %}
{{ block.super }}
<script>
    $(window).load(function () {
        $(function () {
            $('html, body').scrollTop($('#calculation').offset().top);
        });
    });
</script>

{% include 'cupboards/includes/quantity_input_script.html' %}
{% endblock %}

cupboards/templates/cupboards/edit_design.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="logo-font my-4 text-center">Edit Design</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-8 offset-md-2 offset-lg-3 col-lg-6">

                <form method="POST" action="{% url 'edit_design' cupboard.id%}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'main_image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-center my-4">
                        <button class="btn red-theme-color cancel-btn rounded-0 font-weight-bold" type="submit">Edit</button>
                        <a class="btn light-theme-color rounded-0 font-weight-bold cancel-btn" href="{%url 'cupboards'%}?type=cupboard,shelving">Cancel</a>
                    </div>
                </form>
            </div>            
        </div>       
    </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

cupboards/templates/cupboards/edit_material.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="logo-font my-4 text-center">Edit Material</h2>
                <hr>
            </div>
        </div>

        <div class="row">

        <div class="col-12 col-md-6 offset-md-3">

            <form method="POST" action="{% url 'edit_material' material.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-center my-4">
                    <button class="btn red-theme-color rounded-0 font-weight-bold cancel-btn" type="submit">Edit</button>
                    <a class="btn light-theme-color cancel-btn rounded-0 font-weight-bold border-black" href="{%url 'materials'%}">Cancel</a>
                </div>
            </form>
         
        </div>  
        </div>       
    </div>
    </div>
{% endblock %}